#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import json
from dataclasses import asdict, dataclass
from pathlib import Path


C = 960
H_KV = 5
D_HEAD = 64
FFN_DIM = 2560
NUM_LAYERS = 32
VOCAB = 49280
MODEL_MAX_SEQ = 8192
HW_MAX_SEQ = 2048

VIT_TOKENS = 1024
VIT_C = 768
IMAGE_TOKENS = 64
CONNECTOR_IN = 12288
CONNECTOR_OUT = 960


@dataclass
class TransferRow:
    phase: str
    component: str
    direction: str
    bytes: int
    count: int
    total_bytes: int
    note: str


@dataclass
class TransferSavings:
    name: str
    bytes: int
    note: str


def seq_cap_mode() -> str:
    return "restricted" if MODEL_MAX_SEQ != HW_MAX_SEQ else "native"


def packed_w4_bytes(k: int, n: int) -> int:
    return k * n // 2


def meta_bytes(k: int, n: int) -> int:
    return n * (k // 32) * 2


def mib(n: int | float) -> float:
    return float(n) / (1024 * 1024)


def add(rows: list[TransferRow], phase: str, component: str, direction: str, bytes_: int, count: int, note: str) -> None:
    rows.append(TransferRow(phase, component, direction, bytes_, count, bytes_ * count, note))


def decoder_layer_bytes() -> tuple[int, int]:
    matrices = [
        (C, C + H_KV * D_HEAD * 2),
        (C, C),
        (C, FFN_DIM * 2),
        (FFN_DIM, C),
    ]
    return (
        sum(packed_w4_bytes(k, n) for k, n in matrices),
        sum(meta_bytes(k, n) for k, n in matrices),
    )


def parse_args() -> argparse.Namespace:
    root = Path(__file__).resolve().parents[1]
    default_export = root / "quant_experiments_awq_repair_20260508_010000" / "w4a8_awq_g32" / "hardware_export"
    parser = argparse.ArgumentParser(description="Estimate DDR transfer pressure from hardware_export manifest.")
    parser.add_argument("export_dir", nargs="?", type=Path, default=default_export)
    parser.add_argument("--manifest-name", default="hardware_export_manifest.json")
    parser.add_argument("--prefill-len", type=int, default=128)
    parser.add_argument("--decode-steps", type=int, default=32)
    parser.add_argument("--csv-out", type=Path, default=None)
    parser.add_argument("--json-out", type=Path, default=None)
    return parser.parse_args()


def build_rows(manifest: dict, prefill_len: int, decode_steps: int) -> list[TransferRow]:
    rows: list[TransferRow] = []
    decoder_w, decoder_m = decoder_layer_bytes()
    act_prefill = prefill_len * C
    act_decode = C
    gamma = C * 2
    kv_new_per_layer = H_KV * D_HEAD * 2 // 2
    kv_hist_decode_avg = H_KV * D_HEAD * max(decode_steps, 1) // 2
    lmhead_w = packed_w4_bytes(C, VOCAB)
    lmhead_m = meta_bytes(C, VOCAB)
    logits = VOCAB * 4

    add(rows, "prefill", "decoder_weight", "read", decoder_w, NUM_LAYERS, "dominant per-layer stream")
    add(rows, "prefill", "decoder_meta", "read", decoder_m, NUM_LAYERS, "group metadata stream")
    add(rows, "prefill", "decoder_activation", "read+write", act_prefill * 2, NUM_LAYERS, "ping/pong between decoder layers")
    add(rows, "prefill", "gamma", "read", gamma, NUM_LAYERS, "can be cached or duplicated in BRAM")
    add(rows, "prefill", "kv_cache_new", "write", kv_new_per_layer * prefill_len, NUM_LAYERS, "K/V generated by current prompt")

    add(rows, "decode", "decoder_weight", "read", decoder_w, NUM_LAYERS * decode_steps, "same layer weights reread each token")
    add(rows, "decode", "decoder_meta", "read", decoder_m, NUM_LAYERS * decode_steps, "same layer metadata reread each token")
    add(rows, "decode", "decoder_activation", "read+write", act_decode * 2, NUM_LAYERS * decode_steps, "small relative to weights")
    add(rows, "decode", "kv_cache_history", "read", kv_hist_decode_avg, NUM_LAYERS, "rough triangular decode history traffic")
    add(rows, "decode", "kv_cache_new", "write", kv_new_per_layer, NUM_LAYERS * decode_steps, "new token K/V")
    add(rows, "decode", "lmhead", "read", lmhead_w + lmhead_m, decode_steps, "last layer only, still large per generated token")
    add(rows, "decode", "logits", "write", logits, decode_steps, "PS sampling path")

    vision_layers = manifest.get("vision_layers", [])
    vision_w = sum(packed_w4_bytes(layer["K"], layer["N"]) for layer in vision_layers)
    vision_m = sum(meta_bytes(layer["K"], layer["N"]) for layer in vision_layers)
    connector_w = packed_w4_bytes(CONNECTOR_IN, CONNECTOR_OUT)
    connector_m = meta_bytes(CONNECTOR_IN, CONNECTOR_OUT)
    vit_hidden_bridge = VIT_TOKENS * VIT_C * 4
    image_token_bridge = IMAGE_TOKENS * CONNECTOR_OUT * 4

    add(rows, "vision", "vision_weight_meta", "read", vision_w + vision_m, 1, "once per image")
    add(rows, "vision", "vit_hidden_bridge", "write+read", vit_hidden_bridge * 2, 1, "current separate kernel bridge")
    add(rows, "connector", "connector_weight_meta", "read", connector_w + connector_m, 1, "once per image")
    add(rows, "connector", "image_tokens_bridge", "write+read", image_token_bridge * 2, 1, "avoidable connector->decoder DDR bridge")
    return rows


def build_savings() -> list[TransferSavings]:
    image_token_bridge = IMAGE_TOKENS * CONNECTOR_OUT * 4
    decoder_w, decoder_m = decoder_layer_bytes()
    per_token_weight_meta = (decoder_w + decoder_m) * NUM_LAYERS
    return [
        TransferSavings(
            "ps_roundtrip_removed_bytes",
            image_token_bridge * 2,
            "CPU no longer syncs image_tokens back and rewrites decoder act_ping; DDR bridge remains in v1.",
        ),
        TransferSavings(
            "v2_prefill_weight_meta_saved_bytes",
            0,
            "Prefill tile-resident reuse is a structural target; byte savings need Linux-side tile implementation to quantify precisely.",
        ),
        TransferSavings(
            "exact_decode_weight_meta_saved_bytes",
            0,
            "Exact single-request autoregressive decode must sample token t before token t+1 is known, so token-window reuse is not directly available.",
        ),
        TransferSavings(
            "decode_window2_batch_or_speculative_weight_meta_saved_bytes",
            per_token_weight_meta // 2,
            "Window=2 upper-bound only for batched requests, accepted speculative tokens, or already-known token windows.",
        ),
    ]


def write_csv(path: Path, rows: list[TransferRow]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as fp:
        writer = csv.DictWriter(fp, fieldnames=list(asdict(rows[0]).keys()))
        writer.writeheader()
        for row in rows:
            writer.writerow(asdict(row))


def main() -> int:
    args = parse_args()
    manifest = json.loads((args.export_dir / args.manifest_name).read_text(encoding="utf-8"))
    rows = build_rows(manifest, args.prefill_len, args.decode_steps)
    savings = build_savings()
    totals: dict[str, int] = {}
    for row in rows:
        totals[row.phase] = totals.get(row.phase, 0) + row.total_bytes

    if args.csv_out:
        write_csv(args.csv_out, rows)
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(
            json.dumps({
                "rows": [asdict(row) for row in rows],
                "totals": totals,
                "savings": [asdict(item) for item in savings],
            }, indent=2),
            encoding="utf-8",
        )

    print("=== Transfer Budget Estimate ===")
    print(f"export_dir: {args.export_dir}")
    print(f"manifest: {args.manifest_name}")
    print(f"status: {manifest.get('kv260_status')}")
    print(f"model_max_seq: {MODEL_MAX_SEQ}")
    print(f"hw_max_seq: {HW_MAX_SEQ}")
    print(f"seq_cap_mode: {seq_cap_mode()}")
    print()
    for phase in ("vision", "connector", "prefill", "decode"):
        phase_rows = [row for row in rows if row.phase == phase]
        if not phase_rows:
            continue
        print(f"{phase}: {mib(totals[phase]):.2f} MiB")
        for row in phase_rows:
            print(f"  {row.component:<22} {row.direction:<10} {mib(row.total_bytes):8.2f} MiB  {row.note}")
        print()

    decoder_w, decoder_m = decoder_layer_bytes()
    one_decode_layer = decoder_w + decoder_m + C * 2
    print("Data-transfer conclusions:")
    print(f"  decoder layer rereads about {mib(decoder_w + decoder_m):.2f} MiB of weight/meta per launch")
    print(f"  one decode token across 32 layers is about {mib(one_decode_layer * NUM_LAYERS):.2f} MiB before lm_head")
    print("  connector->decoder image token bridge is small, but removing it is the cleanest first fusion step")
    for item in savings:
        print(f"  {item.name}: {mib(item.bytes):.2f} MiB ({item.note})")
    print("  the biggest structural win is reducing per-token decoder weight/meta rereads, not adding more MACs")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
